### ISSUE TITLE
Add to tab group key binding masked by global keygraber for layout switcher

### ISSUE THREAD

**Issue by Ryex** [Kasper24/KwesomeDE#16]
The Alt+a keybinding to add clients to tabgroups is currently masked by the global keygrabber at lines `959` and `975` in `config/keys/lua`.

pressing Alt+a brings up the layout switcher whcih stays up for as long as you hold a. howerver the keybinding Mod+a is isted as adding client to tab groups in the keybindings listed in the `F1` keybindings page  as the first item in the `client` group.

I've remapped the layout switcher key to x in my own configs for now as it didn't seem to have other mappings.

As an asside I think it would be nice to do a bit of themeing adjustment for the bling Tabbed module to reduce the heige of the tabs.
looking at the setting `theme.tabber_*` setting in theme.lua lead to be setting the font size to 9 and wrapping the height call with `dpi` which worked nicely for me to bring it inline with my setup.

def not a priority though.
This config is really polishing up nicely.

**Comment by Kasper24** [comment]
Does it work better now?

**Comment by Ryex** [comment]
This is better now yes.


Though new reset to the default dpi setting made things unusable for me untill a maunualy changed it to 48 in the settings json and restarted. The settings app was laarger then my screen! (1400x900)

you may want to try some of your things out at lower DPIs some of them seem to break. IE in the settings app some of the description text get cut off.

**Comment by Kasper24** [comment]
What's getting cutoff, the text inside the text inputs?
Regarding the settings app size I'm aware of that, but the reason I have it this jig and with a fixed size is because of the wallpaper grid inside the theme tab. It's possible to make the grid increase the number of rows/columns based on the app width/height, and then I could make the settings app resize able and possibly spawn it with a smaller size, but it would require some work

**Comment by Ryex** [comment]
The particular case I was thinking of with the Settings app was the "Show lockscreen at login" text was cutoff at the second e in "lockscreen" by it's checkbox. I had to grep the source to read it's description.

Other cases are thing like the record and screen shot app the buttons get squished and the tops and bottoms of the text are cut off. same with the input text for the save location.

The Dropdown to select resolution in the record applet dissapears as soon as I try to hovor it.

**Comment by Kasper24** [comment]
> Other cases are thing like the record and screen shot app the buttons get squished and the tops and bottoms of the text are cut off. same with the input text for the save location.

Can you upload an image of this? I tested with a DPI of 48 and I don't see that

**Comment by Ryex** [comment]
![image](https://user-images.githubusercontent.com/508861/229391149-24ebcad1-8397-41b8-88fe-995ccda5891b.png)

**Comment by Kasper24** [comment]
How does it look after the recent committs?
