### ISSUE TITLE
Lock-Screen modules

### ISSUE THREAD

**Issue by jyuangrace** [Kasper24/KwesomeDE#17]
Hi Kasper, I really love your awesomewm configs! Is it possible if you can make a lockscreen folder module, so that I can use it for my seperate awesomewm from Rxyhn's Yoru?

**Comment by Kasper24** [comment]
It depends on a lot of my other widgets and the system daemons, so it's not really something I want to do. Though you can extract all that code yourself and use in rxhyn rice
