### ISSUE TITLE
kwesomeDE does not start 

### ISSUE THREAD

**Issue by alavaelian** [Kasper24/KwesomeDE#18]
i have installed awesome wm from the github in a debian 12 book worm system it compiled with no issues and it have running, i installed kwesome but i can not get it running , i really want to test it but i have tried like four times and i have not being hable to get it running.

i tired to run it with xephyr in an tested session and i got  this log
```
error while running function!
stack traceback:
        [C]: in function 'collectgarbage'
        /home/unlinuxeromas/.config/awesome/rc.lua:6: in main chunk
error: /home/unlinuxeromas/.config/awesome/rc.lua:6: bad argument #1 to 'collectgarbage' (invalid option 'incremental')
error while running function!
stack traceback:
        /home/unlinuxeromas/.config/awesome/ui/widgets/text.lua:150: in function </home/unlinuxeromas/.config/awesome/ui/widgets/text.lua:136>
        (...tail calls...)
        ...unlinuxeromas/.config/awesome/wibox/widget/textclock.lua:178: in function <...unlinuxeromas/.config/awesome/wibox/widget/textclock.lua:177>
        (...tail calls...)
        /usr/local/etc/xdg/awesome/rc.lua:122: in main chunk
error: /home/unlinuxeromas/.config/awesome/ui/widgets/text.lua:150: attempt to index a nil value (field 'colors')
2023-06-19 10:12:40 E: awesome: main:875: couldn't find any rc file
```

**Comment by Kasper24** [comment]
Are you using the latest awesome version? it should be built against Lua 5.4 which has the new collectgarbage settings

**Comment by alavaelian** [comment]
hey man thanks so much for answer on my way to test it

**Comment by alavaelian** [comment]
can you tell me how to   compile awesome with an espefic version of lua in my system i got like  tree lua  version lua5.4 lua5.3 and lua 5.2

**Comment by alavaelian** [comment]
> Are you using the latest awesome version? it should be built against Lua 5.4 which has the new collectgarbage settings.
> 
> For quick fix, change line 6 to the following:
> 
> ```lua
> collectgarbage("collect")
> ```

yes i clone the git repo for installing it

**Comment by Kasper24** [comment]
> can you tell me how to compile awesome with an espefic version of lua in my system i got like tree lua version lua5.4 lua5.3 and lua 5.2

I'm not sure how to do so it Debian, but in the meantime you can change line 6 in rc.lua to this:
```LUA
collectgarbage("collect")
```

**Comment by alavaelian** [comment]
> > can you tell me how to compile awesome with an espefic version of lua in my system i got like tree lua version lua5.4 lua5.3 and lua 5.2
> 
> I'm not sure how to do so it Debian, but in the meantime you can change line 6 in rc.lua to this:
> 
> ```lua
> collectgarbage("collect")
> ```

done but i got other error
`2023-06-23 16:26:52 W: awesome: Can't load Playerctl introspection. Seems like Playerctl is not installed or `lua-lgi` was built with an incompatible Playerctl version. Using playerctl cli instead!
error while running function!
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        .../unlinuxeromas/.config/awesome/daemons/system/system.lua:18: in main chunk
        [C]: in function 'require'
        /home/unlinuxeromas/.config/awesome/ui/screens/power.lua:11: in main chunk
        [C]: in function 'require'
        ...nlinuxeromas/.config/awesome/ui/panels/action/header.lua:7: in main chunk
        [C]: in function 'require'
        .../unlinuxeromas/.config/awesome/ui/panels/action/init.lua:18: in main chunk
        [C]: in function 'require'
        /home/unlinuxeromas/.config/awesome/ui/popups/main_menu.lua:7: in main chunk
        [C]: in function 'require'
        /home/unlinuxeromas/.config/awesome/config/keys.lua:7: in main chunk
        [C]: in function 'require'
        /home/unlinuxeromas/.config/awesome/config/init.lua:8: in main chunk
        [C]: in function 'require'
        /home/unlinuxeromas/.config/awesome/rc.lua:42: in main chunk
error: error loading module 'liblua_pam' from file '/home/unlinuxeromas/.config/awesome/external/pam/liblua_pam.so':
        liblua.so.5.4: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
error while running function!
stack traceback:
        /home/unlinuxeromas/.config/awesome/ui/widgets/text.lua:150: in function </home/unlinuxeromas/.config/awesome/ui/widgets/text.lua:136>
        (...tail calls...)
        ...unlinuxeromas/.config/awesome/wibox/widget/textclock.lua:178: in function <...unlinuxeromas/.config/awesome/wibox/widget/textclock.lua:177>
        (...tail calls...)
        /usr/local/etc/xdg/awesome/rc.lua:122: in main chunk
error: /home/unlinuxeromas/.config/awesome/ui/widgets/text.lua:150: attempt to index a nil value (field 'colors')
2023-06-23 16:26:52 E: awesome: main:875: couldn't find any rc file
`

**Comment by Kasper24** [comment]
This happens because the liblua_pam.so file at external/pam is built against a different LUA version that your AwesomeWM was built against. 

What you want to do it follow the instructions at https://github.com/RMTT/lua-pam and replace the .so file in the external/pam folder.

**Comment by alavaelian** [comment]
thanks for the help man
