### ISSUE TITLE
Awesome app welcome 

### ISSUE THREAD

**Issue by AcoXQ** [Kasper24/KwesomeDE#6]
Hello,
Thank you so much for sharing this nice awesome dots files but i have some problem with them i am beginner and dont know much.
Installed everything and welcomed with app called awesome app welcome this app show me combination what theme i can use and input my mail address and password,github username and weather api key but i cant input text how to do that. 

Have problem with app who needs root password like gnome disk they need input for root password but popup doesnt show and say i failed to input password.

Do you know what creating this problem?

What i need to change to top & left size bar and font size it so big for me?

Again thank you so much for this dots i like very much.

**Comment by Kasper24** [comment]
I have an idea on what's wrong with the welcome prompt, so I'll fix it later. 
For the size being too big, you want to set your dpi through xresources (I'll add a slider in the the manager soon so you can set it through there)

**Comment by AcoXQ** [comment]
Okey. Can you explain little how do in xresources. Thank you so much sharing this awesome dots 💯

**Comment by AcoXQ** [comment]
Looked up on net for dpi in xresources but noting changed my monitor is 1920x1080 27" dpi 82

**Comment by AcoXQ** [comment]
You fixed problem with input but now show error ui/dropdown line 37 attempt to index a nil value

**Comment by Kasper24** [comment]
1. For xresources after you change the dpi run xrdb -merge ~/.Xresources then reload awesome.
2. I'll see if I can find any brave glyph and add it
3. The dropdown is fixed as well now

**Comment by Kasper24** [comment]
1. For xresources after you change the dpi run xrdb -merge ~/.Xresources then reload awesome.
2. I'll see if I can find any brave glyph and add it
3. The dropdown is fixed as well now

**Comment by Kasper24** [comment]
There's now a slidere in the theme manager settings to set the DPI directly, but you would need to restart Awesome for it to take effect
