### ISSUE TITLE
Use lua-pam for lockscreen?

### ISSUE THREAD

**Issue by Ryex** [Kasper24/KwesomeDE#8]
it would be nice to at least have the option to use PAM for the lockscreen password

https://github.com/RMTT/lua-pam/

arch has an aur package https://aur.archlinux.org/packages/lua-pam-git

**Comment by Kasper24** [comment]
I removed it not long ago, figured it was unnecessary when you can set the password via the settings. Does it bring any other advantage?

**Comment by Kasper24** [comment]
Well, it's not secured in any form, but even if I add PAM support back in I'll still have it work for users who don't have PAM installed via the password in the settings file, because I wouldn't want to add another dependency, as recently I tried to remove as many as possible

**Comment by Kasper24** [comment]
I was under the impression that PAM wasn't installed on most systems, but that seems to be wrong so I've switched over to PAM and removed the previous method.

**Comment by Ryex** [comment]
yea. PAM is kinda fundamental to the account architecture of linux
