### ISSUE TITLE
discussion: wireplumber

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [Kasper24/KwesomeDE#9]
Hello, I'm posting here as there isn't a discussion tab.
Do you know of a way to use `wireplumber's mixer-api` via D-Bus as an alternative to `pactl subscribe` or would one have to use the C-api directly?

**Comment by Kasper24** [comment]
Wireplumber is not meant for this type of use case, so it doesn't provide the appropriate methods I'd need. If you take a look I've recently added my own bindings to libpulse in the external directory, but I still need to add to bind few last things before I can convert the config to use it.

**Comment by MurdeRM3L0DY** [comment]
Oh that's cool. Would you mind sharing the source code?
